version: '2'

services:
  taged_elasticsearch:
    container_name: taged_elasticsearch
    image: elasticsearch:7.14.1
    restart: always
    expose:
      - 9200
      - 9300
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    environment:
      discovery.type: 'single-node'
    mem_limit: 3g
    networks:
      - taged-network

  taged:
    container_name: taged_container
    image: taged:0.1
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      ELASTICSEARCH_HOST: 'taged_elasticsearch'
    ports:
      - '8001:8000'
    mem_limit: 300m
    volumes:
      - ./static:/home/static
      - ./taged:/home/taged
      - ./taged_web:/home/taged_web
      - ./templates:/home/templates
      - ./db.sqlite3:/home/db.sqlite3
      - ./test.py:/home/test.py
    depends_on:
      - taged_elasticsearch
    networks:
      - taged-network


networks:
  taged-network:
    ipam:
      driver: default
      config:
        - subnet: '10.199.198.0/29'
