version: '2'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.14.1
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      discovery.type: 'single-node'
    mem_limit: 3g
    networks:
      - network

  web:
    container_name: taged
    build: .
    restart: always
    command: /bin/bash /app/run.sh
    environment:
      ELASTICSEARCH_HOST: 'elasticsearch'
      ELASTICSEARCH_request_timeout: 90
    ports:
      - '8001:8000'
    mem_limit: 300m
    volumes:
      - ./static:/app/static
      - ./taged:/app/taged
      - ./taged_web:/app/taged_web
      - ./templates:/app/templates
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
      - ./test.py:/app/test.py
      - ./run.sh:/app/run.sh
      - ./books:/app/books
    depends_on:
      - elasticsearch
    networks:
      - network


networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '10.199.198.0/29'
