version: '3'

services:
  elasticsearch:
    container_name: taged_elasticsearch
    image: elasticsearch:7.14.1
    restart: always
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      discovery.type: 'single-node'
    deploy:
      resources:
        limits:
          memory: "3G"
        reservations:
          memory: "2G"
    healthcheck:
      test: "curl -s localhost:9200 > /dev/null || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - taged-network

  taged:
    build: .
    container_name: taged_container
    image: taged:0.7.1
    restart: always
    command: /bin/bash /app/run.sh
    environment:
      ELASTICSEARCH_HOSTS: 'elasticsearch:9200'
    ports:
      - '80:8000'

    deploy:
      resources:
        limits:
          memory: "300M"
        reservations:
          memory: "200M"

    volumes:
      - ./run.sh:/app/run.sh
      - ./static:/app/static
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
      - ./taged:/app/taged
      - ./taged_web:/app/taged_web
      - ./templates:/app/templates
      - ./test.py:/app/test.py
      - ./books:/app/books
      - ./elasticsearch_control:/app/elasticsearch_control
    depends_on:
      - elasticsearch
      - redis
    networks:
      - taged-network

  redis:
    image: redis
    restart: always
    networks:
      - taged-network
    deploy:
      resources:
        limits:
          memory: "100M"
        reservations:
          memory: "50M"

networks:
  taged-network:
    ipam:
      driver: default
      config:
        - subnet: '10.199.198.0/29'
