services:

  knowledge_base:
    build: .
    image: knowledge_base:1.7
    restart: always
    environment:
      REDIS_CACHE_URL: redis://redis:6379/0
      NOTE_INDEX_NAME: notes
    env_file:
      - /etc/sysconfig/taged
    mem_limit: 300m
    volumes:
      # Чтобы добавлять новые изображения и книги
      - ./media:/app/media
      - ./static:/app/static
      # База данных
      - ${DB_FILE:-./db.sqlite3}:/app/db.sqlite3
    depends_on:
      elasticsearch:
        condition: service_started
      redis:
        condition: service_healthy

    networks:
      - knowledge-base-frontend-network
      - knowledge-base-backend-network

  web:
    image: knowledge_base-nginx:1.7
    build: frontend
    ports:
      - "${BIND_HTTPS:-8443}:443"
      - "${BIND_HTTP:-8000}:80"
    restart: always
    mem_limit: 200m
    volumes:
      # Медиа - картинки, книги
      - ./media:/usr/share/nginx/html/media:ro
      # Статика - CSS, JS
      - ./static:/usr/share/nginx/html/static/:ro

      # Настройки nginx
      - ${NGINX_CONF:-./frontend/nginx/default.conf}:/etc/nginx/conf.d/default.conf:ro
      # Приватный ключ
      # - /etc/ssl/taged/private:/etc/ssl/private/:ro
      # Сертификат и ключи Диффи-Хеллмана
      # - /etc/ssl/taged/certs:/etc/ssl/certs/:ro
    depends_on:
      knowledge_base:
        condition: service_started

    networks:
      - knowledge-base-backend-network

  vect:
    image: knowledge_base-vect:1.7
    build: vectorizer
    env_file:
      - .env-vectorizer
    ports:
      - "{VECTOR_BIND:-127.0.0.1}:{VECTOR_PORT:-9999}:8000"
    volumes:
      - "./hf_models/:/app/.cache"
    networks:
      - knowledge-base-backend-network

  elasticsearch:
    image: elasticsearch:7.14.1
    restart: always
    ports:
      - "{ELASTICSEARCH_BIND:-127.0.0.1}:{ELASTICSEARCH_PORT:-9201}:9200"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms${ES_JAVA_XMS:-1200m} -Xmx${ES_JAVA_XMX:-1200m}
    networks:
      - knowledge-base-backend-network

  redis:
    image: redis
    restart: always
    networks:
      - knowledge-base-backend-network
    mem_limit: 100m
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

networks:
  # Создаем свою сеть, чтобы не было конфликтов с уже существующей
  knowledge-base-frontend-network:
    ipam:
      driver: default
      config:
        - subnet: "${SUBNET_WEB:-10.254.253.0/29}"
  knowledge-base-backend-network:
    ipam:
      driver: default
      config:
        - subnet: "${SUBNET_BACK:-10.254.254.0/29}"