# Generated by Django 3.2.8 on 2022-02-24 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taged_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
